### ISSUE TITLE
on sufficiently new ubuntu: /usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by TimMenninger** [stripe/python-interview-prep#18]
This might be the ultimate of nits, but on sufficiently new versions of Ubuntu (I could be wrong, but I think 22.04 is the first), there is no `python` binary - only `python3`. A hot-fix for Ubuntu users is to `apt-get install python-is-python3`, or to manually call the script with `python3`, or to modify the shabang post-checkout. In any case, `./verify_tls.py`, as written, doesn't execute on off-the-shelf Ubuntu >= 22.04.

Perhaps another viable fix is to change the shabang to `#! /usr/bin/env python3`, though as far as "maximal compatibility" goes, I don't know whether more users have `python` and not `python3` or vice versa. Given that the interview requires `python3.6` or later, I imagine this is a safe change, unless there's a reason it wouldn't work on Windows - I don't have a Windows machine on which to try.

I hope this helps future interviewees.

**Comment by georgevreilly-stripe** [comment]
Thanks for the report. I've tweaked the script and the README.
