### ISSUE TITLE
Given package versions incompatible with Python 3.12

### ISSUE THREAD

**Issue by sbhat98** [stripe/python-interview-prep#19]
## Issue

It seems that the given `requests` and `six` versions are unable to work together in a Python 3.12 environment.

When running in a virtual environment created through the instructions in the README, there is an import error when importing `requests` in the verification file:

```
 ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

Upon searching, this is a [known issue](https://github.com/Datalux/Osintgram/issues/947#issuecomment-1872485426) with the `requests` library that [can be fixed](https://github.com/linkchecker/linkchecker/pull/786) by upgrading to `requests >= 2.25`.

Downgrading to Python 3.11 fixed this issue on my end.

## Reproduction

With a base Python version of 3.12, run the commands from the README:

```sh
python3 -m venv ./interview_env
source ./interview_env/bin/activate
python verify_tls.py
```

Platform: MacOS Sonoma

## Expected Behavior

Since the README says this script should work with Python 3.6 or later, expected the script to exit with 

```
TLS 1.2 supported; no action required.
```

**Comment by georgevreilly-stripe** [comment]
Thanks. Should be fixed by https://github.com/stripe-interview/python-interview-prep/pull/21
